#!/bin/sh

# Git hook for running BashBuilder when the server have received a push

# Reads the input given from git to prevent undefined behaviour,
# but the information is not used inside the build system as it
# allows BashBuilder to be run from various different hooks
while read oldrev newrev refname
do
:
done

# The hook knows where the repository is located on the file system so no need to require it in config.sh
path=$(pwd)
path=${path%%/hooks}

# Calls the build script but discards its output from both stdout and stderr 
bash /"The path to the BashBuilder folder"/build/bashbuilder.sh "$path" >/dev/null 2>&1 &
